title: FAQs
nav:
    - KVM-over-USB Solution:
        - usbkvm/index.md
        - What is USB KVM?: usbkvm/kvm-over-usb.md
        - Why Openterface?: usbkvm/openterface.md
    - Mini-KVM Series: 
        - Openterface Mini-KVM: minikvm/op-minikvm.md