# Project information
site_name: Mini-KVM Openterface | Portable KVM Solution
site_url: https://openterface.com/
site_author: Billy Wang
site_description: One Interface, Stable Fast, Cross-OS

# Repository
# repo_name: Openterface
# repo_url: https://github.com/TechxArtisan/Openterface

# Copyright
copyright: >-
  Copyright &copy; All rights reserved. 2023 <a href="https://www.openterface.com">MiniKVM Openterface</a>, Guangzhou Billio Tech. Co., Ltd. <br>
  <a href="/terms-of-service">Terms of Service</a> |
  <a href="/privacy-policy">Privacy Policy</a> | 
  <a href="#__consent">Cookie Settings</a> | 
  <a href="/contact">Contact Us</a>


extra_css:
  - assets/stylesheets/extra.css

# extra_javascript:
#   - assets/javascripts/extra.js

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  favicon: images/favicon.png
  features:
   - navigation.tabs
   - navigation.sections
   - navigation.top
   - navigation.footer
   - toc.integrate
   - search.suggest
   - search.highlight
   - content.tabs
   - content.code.annotation
   - content.code.copy
  palette:
    primary: deep orange
    accent: custom

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/TechxArtisan
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/TechxArtisan
    - icon: fontawesome/brands/facebook-f
      link: https://www.facebook.com/TechxArtisan
    - icon: fontawesome/brands/discord
      link: https://discord.gg/skfExqDD
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@TechxArtisan
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/company/techxartisan/
  # alternate:
  #   - name: English
  #     link: /
  #     lang: en
    # - name: 中文
    #   link: /zh/
    #   lang: zh
  consent:
    title: Cookie Consent
    description: >- 
      We use cookies to enhance quality of docs content, analyse site effectiveness and needs. 
      By consenting, you help us improve our website. Thanks!
    actions:
      - accept
      - reject
      # - manage
  analytics:
    provider: google
    property: G-EKZEH6QYWT
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/heart
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/heart-broken
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://forms.gle/7AoXW2YCPMfmpRmr5" target="_blank" rel="noopener">feedback form</a>.


markdown_extensions:
  # Enables admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # Enables emoji shortcodes like :+1: or :sunglasses:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search

nav:
  - Home: index.md
  - Documentation:
    - Quick Start: quick-start.md
    - Product Information: product-information.md
    - Comparison: comparison.md
    - Use Cases: use-cases.md
    # - Concepts: concepts.md
    # - App: software.md
    # - Hardware: hardware.md
  - FAQs: faq.md
  - Forum: https://discord.gg/skfExqDD
  - About:
    - Contact: contact.md
    - Policies:
      - Privacy Policy: privacy-policy.md
      - Terms of Service: terms-of-service.md
      - Return, Refunds & Warranty: return-refunds-warranty.md
  # - Download: download.md
  # - FAQ: faq.md