site_name: MiniKVM Openterface Docs
site_description: MiniKVM Openterface Docs

theme:
  name: material
  custom_dir: docs/overrides
  language: en
  logo: assets/logo.png
  favicon: images/favicon.png
  features:
   - navigation.tabs
   - navigation.sections
   - navigation.top
   - navigation.footer
   - toc.integrate
   - search.suggest
   - search.highlight
   - content.tabs
   - content.code.annotation
   - content.code.copy
  palette:
    primary: deep orange
nav:
  - Home: index.md
  - About: about.md
  - Contact: contact.md
  - Docs:
    - Getting Started: getting-started.md
    - Installation: installation.md
    - Usage: usage.md
    - Troubleshooting: troubleshooting.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - License: license.md


extra:
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/
    - icon: fontawesome/brands/discord
      link: https://discord.com/
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/
  alternate:
    - name: English
      link: /
      lang: en
    # - name: 中文
    #   link: /zh/
    #   lang: zh
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our website and whether users
      find what they're searching for. With your consent, you're helping us to
      make our website better.<br>
      <br>
      Cookie授权使用说明：<br>
      我们使用Cookies来识别您的重复访问和偏好，以及衡量我们文档的有效性以及用户是否找到了他们正在寻找的内容。经您同意，您正在帮助我们改善我们的文档。
    # cookies:
    #   analytics:
    #     name: Google Analytics
    #     checked: false

copyright: Copyright &copy; 2023 MiniKVM Openterface

markdown_extensions:
  # Enables admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # Enables emoji shortcodes like :+1: or :sunglasses:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search