# Project information
site_name: Mini-KVM Openterface
site_url: https://openterface.com/
site_author: Billy Wang
site_description: One Interface, Stable Fast, Cross-OS. A portable, open-source KVM Solution.

# Repository
# repo_name: Openterface
# repo_url: https://github.com/TechxArtisan/Openterface

# Copyright
copyright: Copyright &copy; 2023 MiniKVM Openterface, TechxArtisan

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  language: en
  logo: assets/logo.png
  favicon: images/favicon.png
  features:
   - navigation.tabs
   - navigation.sections
   - navigation.top
   - navigation.footer
   - toc.integrate
   - search.suggest
   - search.highlight
   - content.tabs
   - content.code.annotation
   - content.code.copy
  palette:
    primary: deep orange

extra:
  # generator: false   # Disable the credit of Mkdocks Material Credits
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/TechxArtisan
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/TechxArtisan
    - icon: fontawesome/brands/facebook-f
      link: https://www.facebook.com/TechxArtisan
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/TechxArtisan
    - icon: fontawesome/brands/threads
      link: https://www.threads.net/@techxartisan
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@TechxArtisan
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/company/techxartisan/
  # alternate:
  #   - name: English
  #     link: /
  #     lang: en
    # - name: 中文
    #   link: /zh/
    #   lang: zh
  # consent:
  #   description: >- 
  #     <br><strong>Cookie Consent</strong><br>
  #     We use cookies to enhance your web browsing experience, analyse site effectiveness and needs. 
  #     By consenting, you help us improve our website. Thanks!<br>
  #     <br><strong>Cookie 授权说明</strong><br>
  #     我们使用Cookies以提升您的网页浏览体验，分析有效性和需求。您的同意将帮助我们改善网站。谢谢！
    # cookies:
    #   analytics:
    #     name: Google Analytics
    #     checked: false

markdown_extensions:
  # Enables admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  # Enables emoji shortcodes like :+1: or :sunglasses:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search

nav:
  - Home: index.md
  - Product: /#product-close-up
  - Guidelines: /#quick-guidelines
  - Features: /#product-features
  - Cases: /#use-cases
  - Documentation:
    - Quick Start: quick-start.md
    - Specifications: specifications.md
    - Comparison: comparison.md
    - Use Cases: use-cases.md
    # - Concepts: concepts.md
    # - Open-Source App: software.md
    # - Hardware: hardware.md
  # - FAQ: faq.md