# Project information
site_name: Mini-KVM Openterface
site_url: https://openterface.com/
site_author: Billy Wang
site_description: Mini-KVM Openterface is a portable KVM, which allows to control two computers with a single keyboard, mouse and monitor in the same interface. It is a great solution for those who need to work with multiple computers.

# Repository
repo_name: Openterface
repo_url: https://github.com/TechxArtisan/Openterface

# Copyright
copyright: Copyright &copy; 2023 MiniKVM Openterface, TechxArtisan

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  language: en
  logo: assets/logo.png
  favicon: images/favicon.png
  features:
   - navigation.tabs
   - navigation.sections
   - navigation.top
   - navigation.footer
   - toc.integrate
   - search.suggest
   - search.highlight
   - content.tabs
   - content.code.annotation
   - content.code.copy
  palette:
    primary: deep orange

extra:
  # generator: false   # Disable the credit of Mkdocks Material Credits
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/youyoubilly
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/
  alternate:
    - name: English
      link: /
      lang: en
    # - name: 中文
    #   link: /zh/
    #   lang: zh
  # consent:
  #   description: >- 
  #     <br><strong>Cookie Consent</strong><br>
  #     We use cookies to enhance your web browsing experience, analyse site effectiveness and needs. 
  #     By consenting, you help us improve our website. Thanks!<br>
  #     <br><strong>Cookie 授权说明</strong><br>
  #     我们使用Cookies以提升您的网页浏览体验，分析有效性和需求。您的同意将帮助我们改善网站。谢谢！
    # cookies:
    #   analytics:
    #     name: Google Analytics
    #     checked: false

markdown_extensions:
  # Enables admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # Enables emoji shortcodes like :+1: or :sunglasses:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search

nav:
  - Home: index.md
  - Shop: https://www.tindie.com
  - Documentation:
    - Quick Start: quickstart.md
  - FAQ: faq.md