title: Product
nav:
    - index.md
    - Mini-KVM:
        - minikvm/index.md
        - minikvm/whats-in-the-box.md
        - minikvm/features.md
        - minikvm/specifications.md
        - minikvm/how-to-connect.md
        - minikvm/usb-switch.md
        - minikvm/extension-pins.md
        - How It Works: usb-kvm
    - Accessories:
        - accessories/index.md