authors:
  TechxArtisan:
    name: TechxArtisan Studio
    description: A creative studio and community of tech enthusiasts.
    avatar: https://github.com/techxartisan.png

  Openterface:
    name: Openterface
    description: Hi there!
    avatar: https://raw.githubusercontent.com/TechxArtisan/Openterface/main/docs/images/op-avatar.jpg