flatten_single_child_sections: true
nav:
    - Home: index.md
    - FAQs: faq
    - Product: product
    - App: app
    - Use Cases: use-cases.md
    - Reviews: /product/minikvm/reviews/
    - Compliance: compliance.md
    - Shop: https://shop.techxartisan.com
    - Discord: /discord
    - About: about.md
    - Blog: blog
